# Generated by Django 3.1.3 on 2021-02-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
